### ISSUE TITLE
Unclear GPU memory increase issue

### ISSUE THREAD

**Issue by fffffq00** [haosulab/SAPIEN#261]
**System:**
```
Python: 3.12.2
Platform: Linux-6.8.0-49-generic-x86_64-with-glibc2.35
sapien: 3.0.0.dev20250917+57826908
GPU: Intel(R) Graphics (RPL-S)
  Supported: 1
  Present:   1
  cudaId:    -1
  rayTrace:  0
  cudaMode   -1
GPU: NVIDIA GeForce RTX 4090
  Supported: 1
  Present:   1
  cudaId:    0
  rayTrace:  1
  cudaMode   0
GPU: NVIDIA GeForce RTX 4090
  Supported: 1
  Present:   1
  cudaId:    0
  rayTrace:  1
  cudaMode   0
GPU: NVIDIA GeForce RTX 4090
  Supported: 1
  Present:   0
  cudaId:    1
  rayTrace:  1
  cudaMode   0
GPU: NVIDIA GeForce RTX 4090
  Supported: 1
  Present:   0
  cudaId:    1
  rayTrace:  1
  cudaMode   0
GPU: llvmpipe (LLVM 15.0.7, 256 bits)
  Supported: 1
  Present:   1
  cudaId:    -1
  rayTrace:  0
  cudaMode   -1
```

**Describe the bug**
I am using Maniskill to test a custom reinforcement learning task (like spinning a block like gym), and I have found that GPU memory slowly accumulates. I loaded `1024*16` parallel environments during training. 
When the program has been running for about 4 hours, it gives the following error:
```
...
7633 SPS: 30102
7634 Epoch: 3537, global_step=463470592
...
7645   File "/opt/miniconda3/lib/python3.12/site-packages/gymnasium/wrappers/order_enforcing.py", line 56, in step
7646     return self.env.step(action)
7647            ^^^^^^^^^^^^^^^^^^^^^
7648   File "/opt/miniconda3/lib/python3.12/site-packages/mani_skill/envs/sapien_env.py", line 1012, in step
7649     self._elapsed_steps += 1
7650 RuntimeError: CUDA error: an illegal memory access was encountered
7651 CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
7652 For debugging consider passing CUDA_LAUNCH_BLOCKING=1
7653 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Screenshots**
This is the memory allocation information displayed by wandb, which shows that the memory is slowly accumulating (Ignore the solid line, it's another GPU).
<img width="401" height="287" alt="Image" src="https://github.com/user-attachments/assets/28e09a0c-4948-4c3e-9f02-dc44f1926b56" />
I also monitored the changes in pytorch's memory allocation. They are the testing phase, the interaction with the environment phase, and the agent training phase. 
<img width="1208" height="309" alt="Image" src="https://github.com/user-attachments/assets/3791b067-66ad-44db-b16b-0813e5102bd8" />

I then used pynvml to further monitor global GPU memory utilization, and I discovered occasional memory allocation increases when interacting with the environment.
<img width="387" height="303" alt="Image" src="https://github.com/user-attachments/assets/8295e79e-4227-4162-ad28-9e4157041a49" />

Judging from the current situation, it does not seem to be the cause of pytorch, so I think this situation is unclear.
My code is very messy now and it is not convenient to upload. How do you think I can further locate the problem? I am happy to find out it.

**Comment by StoneT2000** [comment]
Can you try running the same code on the standard PickCube-v1 task? And use mani-skill-nightly?

**Comment by fffffq00** [comment]
@StoneT2000  I think you're right. I found that the program ran fine when I set the number of environments to 1024x8. I was trying to replicate the tasks in isaac-gym, so I simply set the same 1024x16 environment size. Perhaps SAPIEN has some underlying differences that prevented me from setting this high. However, I achieved similar performance with 1024x8.
So how do we determine the right setting? By checking the accumulation of GPU memory?

**Comment by StoneT2000** [comment]
Which task in isaac gym lets you run 16x1024 environments? We are essentially using the same backend  so gpu env count scaling should be similar.

For right settings i usually never go beyond 4096. The training efficiency gains are too marginal usually and sometimes worse.

**Comment by fffffq00** [comment]
I test the task of rotating the object. I am using this task to rotate an object. Here is its [configuration](https://github.com/isaac-sim/IsaacGymEnvs/blob/main/isaacgymenvs/cfg/task/ShadowHand.yaml#L8) and it works fine. 
Maybe the link collision for my hand is different? Something I didn't set up exactly like it did. For example, it had [`asset_options.use_physx_armature = True`](https://github.com/isaac-sim/IsaacGymEnvs/blob/main/isaacgymenvs/tasks/shadow_hand.py#L243). I didn't know what that did, so I simply set the armature for the link.
